"""add probabilities to regime_evaluations

Revision ID: 34ebb36c4a14
Revises: 7fdd4f8f4bb3
Create Date: 2026-07-14 16:28:02.363077

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "34ebb36c4a14"
down_revision: str | Sequence[str] | None = "7fdd4f8f4bb3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "regime_evaluations",
        sa.Column("probabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("regime_evaluations", "probabilities")
    # ### end Alembic commands ###
