"""add round_trips table

Revision ID: 7fdd4f8f4bb3
Revises: c3f1a9d27b5e
Create Date: 2026-07-12 10:59:03.993513

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7fdd4f8f4bb3"
down_revision: str | Sequence[str] | None = "c3f1a9d27b5e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "round_trips",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("qty", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("entry_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("exit_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("exit_price", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("pnl", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("holding_seconds", sa.Integer(), nullable=False),
        sa.Column("strategy", sa.String(), nullable=False),
        sa.Column("exit_reason", sa.Text(), nullable=False),
        sa.Column("regime", sa.String(), nullable=True),
        sa.Column("entry_indicators", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("exit_indicators", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.run_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_round_trips_run_entry", "round_trips", ["run_id", "entry_time"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_round_trips_run_entry", table_name="round_trips")
    op.drop_table("round_trips")
    # ### end Alembic commands ###
