//! Promoting config values from a research profile to paper trading.
//!
//! `config/trading/paper.yaml` is hand-authored and protected, so promotion
//! never rewrites it: it regenerates the last layer it extends,
//! `config/generated/paper-promoted.yaml`. Previously promoted values are
//! kept, the selected ones are merged in, and the file is only replaced once
//! the *complete* candidate paper config validates.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{anyhow, Context, Result};
use serde_json::{Map, Value};

use crate::cli::{self, Validation};
use crate::config_tree;

/// The profile promotion writes to.
pub const PAPER_PROFILE: &str = "trading/paper";
/// The generated layer `trading/paper` extends last.
pub const PROMOTED_LAYER: &str = "config/generated/paper-promoted.yaml";

const HEADER: &str = "\
# GENERATED by carcharoth-tui (config promotion) — do not edit by hand.
#
# The last layer of config/trading/paper.yaml: values promoted from a
# research profile. Every write is validated against the full paper profile
# first. Delete an entry here to fall back to the layer below.
";

pub fn promoted_layer_path() -> PathBuf {
    PathBuf::from(PROMOTED_LAYER)
}

/// The leaves currently promoted (empty when the layer does not exist yet).
pub fn load(path: &Path) -> Result<BTreeMap<String, Value>> {
    if !path.exists() {
        return Ok(BTreeMap::new());
    }
    let text =
        fs::read_to_string(path).with_context(|| format!("could not read {}", path.display()))?;
    let value: Value = serde_yaml::from_str(&text)
        .with_context(|| format!("{} is not valid YAML", path.display()))?;
    if value.is_null() {
        return Ok(BTreeMap::new());
    }
    if !value.is_object() {
        return Err(anyhow!("{}: top level must be a mapping", path.display()));
    }
    Ok(config_tree::flatten(&value))
}

/// Previously promoted values with the selected ones applied on top.
pub fn merge(
    existing: &BTreeMap<String, Value>,
    selected: impl IntoIterator<Item = (String, Value)>,
) -> BTreeMap<String, Value> {
    let mut merged = existing.clone();
    for (path, value) in selected {
        // A promoted parent (or child) would fight with the new leaf in the
        // nested document; the newest selection wins.
        merged.retain(|other, _| !is_ancestor(other, &path) && !is_ancestor(&path, other));
        merged.insert(path, value);
    }
    merged
}

fn is_ancestor(candidate: &str, path: &str) -> bool {
    path.starts_with(candidate) && path.as_bytes().get(candidate.len()) == Some(&b'.')
}

/// `{"risk.max_open_positions": 8}` -> `{"risk": {"max_open_positions": 8}}`.
pub fn nest(leaves: &BTreeMap<String, Value>) -> Value {
    let mut root = Map::new();
    for (path, value) in leaves {
        let segments: Vec<&str> = path.split('.').collect();
        let mut node = &mut root;
        for segment in &segments[..segments.len() - 1] {
            node = node
                .entry(segment.to_string())
                .or_insert_with(|| Value::Object(Map::new()))
                .as_object_mut()
                .expect("ancestors were removed on merge");
        }
        node.insert(segments[segments.len() - 1].to_string(), value.clone());
    }
    Value::Object(root)
}

/// The generated layer's file contents: header + deterministic YAML.
pub fn render_layer(leaves: &BTreeMap<String, Value>) -> Result<String> {
    if leaves.is_empty() {
        return Ok(HEADER.to_string());
    }
    let body = serde_yaml::to_string(&nest(leaves)).context("could not serialize promoted YAML")?;
    Ok(format!("{HEADER}\n{body}"))
}

/// `--set` overrides that turn the paper profile into the candidate config.
pub fn candidate_overrides(leaves: &BTreeMap<String, Value>) -> Vec<(String, String)> {
    leaves
        .iter()
        .map(|(path, value)| (path.clone(), config_tree::render(value)))
        .collect()
}

/// Validate the candidate paper config, then replace the generated layer.
///
/// Nothing is written when validation fails, and the successful write goes
/// through a temporary file + rename so the layer is never half-written.
pub fn apply(path: &Path, leaves: &BTreeMap<String, Value>) -> Result<String> {
    let contents = render_layer(leaves)?;
    match cli::validate(PAPER_PROFILE, &candidate_overrides(leaves))? {
        Validation::Invalid { errors } => {
            let details = Validation::Invalid { errors }.summary();
            Err(anyhow!("promotion rejected — {details}"))
        }
        Validation::Valid { hash } => {
            write_atomically(path, &contents)?;
            Ok(hash)
        }
    }
}

fn write_atomically(path: &Path, contents: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("could not create {}", parent.display()))?;
    }
    let temporary = path.with_extension("yaml.tmp");
    fs::write(&temporary, contents)
        .with_context(|| format!("could not write {}", temporary.display()))?;
    fs::rename(&temporary, path)
        .with_context(|| format!("could not replace {}", path.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn leaves(pairs: &[(&str, Value)]) -> BTreeMap<String, Value> {
        pairs
            .iter()
            .map(|(path, value)| (path.to_string(), value.clone()))
            .collect()
    }

    fn scratch(name: &str) -> PathBuf {
        let dir =
            std::env::temp_dir().join(format!("carcharoth-tui-{}-{name}", std::process::id()));
        fs::create_dir_all(&dir).unwrap();
        dir.join("paper-promoted.yaml")
    }

    #[test]
    fn missing_layer_starts_empty() {
        let path = scratch("missing").with_file_name("nope.yaml");
        assert!(load(&path).unwrap().is_empty());
    }

    #[test]
    fn merge_keeps_previous_promotions_and_lets_new_ones_win() {
        let existing = leaves(&[
            ("risk.max_open_positions", json!(8)),
            ("symbols", json!(["AAPL"])),
        ]);
        let merged = merge(
            &existing,
            vec![("symbols".to_string(), json!(["SPY", "QQQ"]))],
        );
        assert_eq!(merged["risk.max_open_positions"], json!(8));
        assert_eq!(merged["symbols"], json!(["SPY", "QQQ"]));
    }

    #[test]
    fn merge_drops_conflicting_ancestors_and_descendants() {
        let existing = leaves(&[("regime.hmm.n_states", json!(4))]);
        let merged = merge(
            &existing,
            vec![("regime.hmm".to_string(), json!({"n_states": 3}))],
        );
        assert_eq!(merged.len(), 1);
        assert_eq!(merged["regime.hmm"], json!({"n_states": 3}));
    }

    #[test]
    fn nesting_rebuilds_the_layer_document() {
        let nested = nest(&leaves(&[
            ("risk.max_open_positions", json!(8)),
            ("strategies.mean_reversion.params.entry_z", json!(-1.5)),
            ("symbols", json!(["SPY"])),
        ]));
        assert_eq!(
            nested,
            json!({
                "risk": {"max_open_positions": 8},
                "strategies": {"mean_reversion": {"params": {"entry_z": -1.5}}},
                "symbols": ["SPY"]
            })
        );
    }

    #[test]
    fn rendered_layer_is_deterministic_and_marked_generated() {
        let selection = leaves(&[
            ("symbols", json!(["SPY"])),
            ("risk.max_open_positions", json!(8)),
        ]);
        let text = render_layer(&selection).unwrap();
        assert!(text.starts_with("# GENERATED by carcharoth-tui"));
        assert_eq!(text, render_layer(&selection).unwrap());
        // keys sorted: risk before symbols
        let risk = text.find("risk:").unwrap();
        assert!(risk < text.find("symbols:").unwrap());
    }

    #[test]
    fn empty_selection_renders_only_the_header() {
        assert_eq!(render_layer(&BTreeMap::new()).unwrap(), HEADER);
    }

    #[test]
    fn layer_round_trips_through_yaml() {
        let path = scratch("roundtrip");
        let selection = leaves(&[
            ("risk.max_open_positions", json!(8)),
            ("strategies.mean_reversion.params.entry_z", json!(-1.5)),
            ("symbols", json!(["SPY", "QQQ"])),
        ]);
        write_atomically(&path, &render_layer(&selection).unwrap()).unwrap();
        assert_eq!(load(&path).unwrap(), selection);
        assert!(!path.with_extension("yaml.tmp").exists());
        fs::remove_file(&path).unwrap();
    }

    #[test]
    fn comment_only_layer_loads_as_empty() {
        let path = scratch("headeronly");
        write_atomically(&path, HEADER).unwrap();
        assert!(load(&path).unwrap().is_empty());
        fs::remove_file(&path).unwrap();
    }

    #[test]
    fn candidate_overrides_use_cli_value_syntax() {
        let overrides = candidate_overrides(&leaves(&[
            ("symbols", json!(["SPY"])),
            ("quicktest.strategy", json!("mean_reversion")),
        ]));
        assert_eq!(
            overrides,
            vec![
                (
                    "quicktest.strategy".to_string(),
                    "mean_reversion".to_string()
                ),
                ("symbols".to_string(), r#"["SPY"]"#.to_string()),
            ]
        );
    }
}
